### ISSUE TITLE
TCP API connection closing ends all connections from that IP

### ISSUE THREAD

**Issue by ScriptBlock** [meshtastic/Meshtastic-device#608] opened 2020-12-30 04:15 UTC
Scenario:
Server 1 launches messagelistener.py
   messagelistener.py begins TCP connection to meshtastic API.  
   Subscribes to meshtastic.receive.  
   Begins receiving message.  
   Begins looping, waiting for messages - delivering downstream once received.  
This continues to run indefinitely.

Server 1 launches info.py
   info.py begins TCP connection to meshtastic API.  
   Subscribes to meshtastic.connection.established. 
   Once connection is made, queries interface.myInfo 
info.py closes the connection.

Once info.py completes, messagelistener.py no longer receives any messages, but also throws no errors.  I can't tell if this is a problem with the API making multiple TCP connections or if the device is closing all API connections for a given IP.

I realize that this may not be the desired implementation of the API (i.e. - multiple TCP API requests from the same machine).  In which case I can modify things to use a single thread/script, but it's less than ideal in this case.

Thanks!

**Comment by mc-hamster** [comment] 2021-03-27 06:20
Closing as duplicate of https://github.com/meshtastic/Meshtastic-device/issues/526

**Closed by mc-hamster** 2021-03-27 06:20 UTC
