### ISSUE TITLE
Consistant Failure of initial BLE Pairing for ESP32 BLE 4.0 Devices

### ISSUE THREAD

**Issue by garthvh** [meshtastic/Meshtastic-device#1055] opened 2022-01-03 02:15 UTC
It seems the custom pin pairing code we are currently doing to connect to BLE devices is causing some crashing / inability to pair BLE 4.0 ESP32 devices on iOS and recent android versions (10+)

**To Reproduce**
 
Forget the device and attempt to pair a tbeam, lora32 or Heltec device with the iOS or Android app.

It seems like this update may be a good time to set up just works and pin based pairing for all devices. And settle on a default (I would vote for no pin as default since it seems users fat finger the pin about 25% of the time.)

**Comment by mc-hamster** [comment] 2022-01-04 00:26
The cause of this may be similar to the Android pairing problems we've been seeing.

**Comment by mc-hamster** [comment] 2022-01-04 17:30
I had a device that couldn't be discovered by iOS or android. After erasing the flash and reinstalling firmware, the device worked with ble again.

This suggests the problem may not only be with pin pairing.

**Comment by garthvh** [comment] 2022-01-04 17:59
Had it worked previously or was it a brand new device?  In my experience only devices with PINs do that strange disappearing devices that use just works don't really seem to have any details saved in iOS at least.

**Comment by mc-hamster** [comment] 2022-01-04 18:24
I don’t use clients enough to be able to answer that question.

**Comment by mc-hamster** [comment] 2022-01-07 06:26
Disabling MITM made pairing reliable but had other problems.

**Comment by thebentern** [comment] 2022-05-14 01:20
@garthvh is this solved on 1.3 with the new bluetooth platform? If so, I'd like to close it.

**Comment by garthvh** [comment] 2022-05-14 01:36
Seems to be solved in 1.3

**Comment by thebentern** [comment] 2022-05-14 12:45
Closing. We can reopen a new issue if anything crops up on 1.3.

**Closed by thebentern** 2022-05-14 12:45 UTC
Labels: bug
