### ISSUE TITLE
Enhancement: Personalized network branding

### ISSUE THREAD

**Issue by LolloDev5123** [meshtastic/Meshtastic-device#1309] opened 2022-03-19 14:04 UTC
A setting that over-rides the "Meshtastic_" prefix in bluetooth or wifi hotspots, or even change the whole name?

**Comment by garthvh** [comment] 2022-03-20 01:20
Duplicate of https://github.com/meshtastic/Meshtastic-device/issues/657

**Closed by garthvh** 2022-03-20 01:20 UTC

**Comment by LolloDev5123** [comment] 2022-03-20 11:50
This does not apply only to Bluetooth, includes some other ideas which I was asked to open in a diff issue
