### ISSUE TITLE
The meassage queue needs to be rewrited because the messages transmitted to the channel in in unordered 

### ISSUE THREAD

**Issue by IRainman** [meshtastic/Meshtastic-device#834] opened 2021-08-07 13:42 UTC
I use T-Echo with version 1.2.43. I see the history of the last commit and probably problem is happend after this commit: https://github.com/meshtastic/Meshtastic-device/commit/986d44873a464fe97d09a26260f55e7e7f3f106c

We realy need to use std::queue for the queue ;) std::unordred_set is unusable here! Please don't broke the functionality! Ordering of message is realy need to be same as message are realy sended 

![Screenshot_20210807-163816](https://user-images.githubusercontent.com/3396559/128602177-8c4d9787-09d0-4c1a-a4c5-88cd3b2444c8.jpg)
![Screenshot_20210807-163920](https://user-images.githubusercontent.com/3396559/128602180-1f21a5c8-9ab2-4eec-ac2d-c392a1b3d27b.jpg)

**Comment by garthvh** [comment] 2022-01-22 14:33
This is working properly on all of my devices and we don't have any other reports of this issue, can we close this?

**Comment by mc-hamster** [comment] 2022-01-22 17:31
Closed

**Closed by mc-hamster** 2022-01-22 17:31 UTC

**Comment by garthvh** [comment] 2023-02-13 20:16
> i have this bug too, please help is not going order

There are potentially delays for transmitting and receiving, order is not guaranteed, this is not a bug

**Comment by IRainman** [comment] 2023-02-14 12:41
> > i have this bug too, please help is not going order
> 
> There are potentially delays for transmitting and receiving, order is not guaranteed, this is not a bug

This is unusual at all. The protocol is needs to be updated.
