### ISSUE TITLE
Set Fixed Position changed back to GPS Postion after some time[Bug]: 

### ISSUE THREAD

**Issue by Bergstern** [meshtastic/Meshtastic-device#1680] opened 2022-09-08 15:55 UTC
### Category

Other

### Hardware

Rak4631

### Firmware Version

1.3.40.e87ecc2-d

### Description

When set a fixed position with the command "meshtastic --setlat 50 --setlon 50" the cli confirmed the changes and at the meshtastic info there are the right coords. After a while the coords. jumped back to the gps coordinates of the current position of the node. "hasGps": is at true, should be at false.

**Comment by garthvh** [comment] 2022-09-11 14:40
hasGPS indicates that there is a hardware GPS, disabling it does not flip this boolean

**Comment by garthvh** [comment] 2022-09-11 14:43
You also need to disable GPS for this to work, as "meshtastic --setlat 50 --setlon 50" just adds a regular position and fixed position uses the last set position, if gps is on that position will be updated based on the GPS settings.

**Comment by Bergstern** [comment] 2022-09-11 18:11
![Screenshot_2022-09-10-15-22-28-89_24570ffaa6dee6a40011f001254fdfdb__01.jpg](https://user-images.githubusercontent.com/64352553/189542630-e517e68a-e2aa-4876-9de8-12bcd22791d7.jpg)

**Comment by Bergstern** [comment] 2022-09-11 18:13
Thats displaed at the debug from the android software. Gps already is disabled. Thats reason i think its a bug. If i set gps at disabled and set a fixed position the gps should turn off?

**Comment by garthvh** [comment] 2022-09-11 20:52
yeah seems like a bug, I think this feature is mostly used to add location when a device has a gps, but it seems like it should use the fixed location and turn off the gps if the gps is disabled and fixed position is set. @thebentern seem right?

**Comment by caveman99** [comment] 2022-10-04 13:32
GPS won't turn off until after next reboot if it is set to false. @Bergstern can you double check these settings, then reboot the device and set a fixed position? that should not change any more.

**Comment by Bergstern** [comment] 2022-10-09 07:41
@caveman99 i cant test it for now because i dismount the gps module. And the rak isnt at home at the moment. Sry

**Comment by caveman99** [comment] 2022-10-12 11:45
closing for now cause i can't reproduce. Please reopen if still a problem.

**Closed by caveman99** 2022-10-12 11:45 UTC
Labels: bug, question

**Comment by IZ1IVA** [comment] 2022-10-14 07:27
Setting a fixed position is still not reliable on 1.3.44 on tlora-v2-1-1.6 and not possibile at all on tbeam.
