### ISSUE TITLE
Allow device to route between internet and LoRa

### ISSUE THREAD

**Issue by texrg** [meshtastic/Meshtastic-device#8] opened 2020-02-28 10:47 UTC
I think, many people need a router version. With ethernet cable.
Increase network and comunicating from/to internet
For example tox, matrix, wire <-> to lora

**Comment by geeksville** [comment] 2020-02-28 16:56
oh yes, this is definitely a good idea, though given the limited bandwidth of LoRa I think the existing bluetooth (or serial via USB) link is probably sufficient.

**Comment by geeksville** [comment] 2021-01-28 03:08
also - this feature will be built on top of https://github.com/meshtastic/Meshtastic-device/issues/169 (mqtt gateway support)

**Comment by mc-hamster** [comment] 2021-03-26 02:57
Closing as duplicate of #169

**Closed by mc-hamster** 2021-03-26 02:57 UTC
Labels: duplicate, enhancement
