### ISSUE TITLE
[Bug]: Missing 1.3.39.ddc3727/spiffs-1.3.39.ddc3727.bin when using meshtastic-flasher?

### ISSUE THREAD

**Issue by Walt-1000** [meshtastic/Meshtastic-device#1655] opened 2022-08-27 06:52 UTC
### Category

Other

### Hardware

T-Beam

### Firmware Version

1.3.39.ddc3727

### Description

When attempting to upgrade to firmware 1.3.39.ddc3727 this message below appeared in the meshtastic-flasher tool:

Step 3/4 esp32 full
ESPTOOL Using command:-b 921600 --port /dev/ttyACM0 write_flash 0x00390000 1.3.39.ddc3727/spiffs-1.3.39.ddc3727.bin
usage: esptool write_flash [-h] [--erase-all]
                           [--flash_freq {keep,80m,60m,48m,40m,30m,26m,24m,20m,16m,15m,12m}]
                           [--flash_mode {keep,qio,qout,dio,dout}]
                           [--flash_size FLASH_SIZE]
                           [--spi-connection SPI_CONNECTION] [--no-progress]
                           [--verify] [--encrypt]
                           [--encrypt-files <address> <filename> [<address> <filename> ...]]
                           [--ignore-flash-encryption-efuse-setting]
                           [--compress | --no-compress]
                           <address> <filename> [<address> <filename> ...]
esptool write_flash: error: argument <address> <filename>: [Errno 2] No such file or directory: '1.3.39.ddc3727/spiffs-1.3.39.ddc3727.bin'

### Relevant log output

```Shell
Step 1/4 esp32 full
ESPTOOL Using command:-b 921600 --port /dev/ttyACM0 erase_flash
esptool.py v3.3.1
Serial port /dev/ttyACM0
Connecting...

.

.


Detecting chip type...

Unsupported detection protocol, switching and trying again...
Connecting...

.


Detecting chip type...

ESP32


Chip is ESP32-D0WDQ6-V3 (revision 3)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
WARNING: Detected crystal freq 41.01MHz is quite different to normalized freq 40MHz. Unsupported crystal in use?
Crystal is 40MHz
MAC: 30:c6:f7:1e:2a:00
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Erasing flash (this may take a while)...
Chip erase completed successfully in 9.8s
Hard resetting via RTS pin...
Step 2/4 esp32 full
ESPTOOL Using command:-b 921600 --port /dev/ttyACM0 write_flash 0x1000 1.3.39.ddc3727/system-info.bin
esptool.py v3.3.1
Serial port /dev/ttyACM0
Connecting...

.


Detecting chip type...

Unsupported detection protocol, switching and trying again...
Connecting...

.

.

.


Detecting chip type...

ESP32


Chip is ESP32-D0WDQ6-V3 (revision 3)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 30:c6:f7:1e:2a:00
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...
Flash will be erased from 0x00001000 to 0x0000ffff...
Compressed 61440 bytes to 11950...
Writing at 0x00001000... (100 %)
Wrote 61440 bytes (11950 compressed) at 0x00001000 in 1.1 seconds (effective 440.4 kbit/s)...
Hash of data verified.
Leaving...
Hard resetting via RTS pin...
Step 3/4 esp32 full
ESPTOOL Using command:-b 921600 --port /dev/ttyACM0 write_flash 0x00390000 1.3.39.ddc3727/spiffs-1.3.39.ddc3727.bin
usage: esptool write_flash [-h] [--erase-all]
                           [--flash_freq {keep,80m,60m,48m,40m,30m,26m,24m,20m,16m,15m,12m}]
                           [--flash_mode {keep,qio,qout,dio,dout}]
                           [--flash_size FLASH_SIZE]
                           [--spi-connection SPI_CONNECTION] [--no-progress]
                           [--verify] [--encrypt]
                           [--encrypt-files <address> <filename> [<address> <filename> ...]]
                           [--ignore-flash-encryption-efuse-setting]
                           [--compress | --no-compress]
                           <address> <filename> [<address> <filename> ...]
esptool write_flash: error: argument <address> <filename>: [Errno 2] No such file or directory: '1.3.39.ddc3727/spiffs-1.3.39.ddc3727.bin'
```

**Comment by garthvh** [comment] 2022-08-27 07:02
Duplicate of https://github.com/meshtastic/Meshtastic-device/issues/1643

**Closed by garthvh** 2022-08-27 07:02 UTC
Labels: bug, duplicate
