### ISSUE TITLE
[Bug]: screen_on_secs to non zero value causes instant screen off

### ISSUE THREAD

**Issue by rohanki** [meshtastic/Meshtastic-device#1659] opened 2022-08-28 01:58 UTC
### Category

Other

### Hardware

T-Beam

### Firmware Version

1.3.39.ddc3727

### Description

Setting a value for screen_on_secs to anything seems to cause the screen to turn off more or less instantly. Pressing the user button will turn the screen on for under a second (just a flash really) and then switch off again. I've tried a bunch of values (10-300 seconds) and all exhibit the same behaviour.
After setting screen_on_secs back to 0 and resetting the device, screen behaves as normal.

I used python 1.3a25 to set screen_on_secs, which appears to have applied correctly. "display": { "screenOnSecs": 60 }
Have replicated the issue with 2 tbeam's and one t-lora v2.1-1.6.
I'm not sure how to get any debug logs - screen is always on when connected to USB.

**Comment by garthvh** [comment] 2022-08-28 03:38
Duplicate of https://github.com/meshtastic/Meshtastic-device/issues/1553

**Closed by garthvh** 2022-08-28 03:38 UTC
Labels: bug, duplicate
