### ISSUE TITLE
add range test export over serial interface

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-device#1389] opened 2022-04-19 04:30 UTC
add range test export over serial interface

triggered by a radioconfig enum, writes over serial using a delimited format with a defined header and footer.

**Comment by garthvh** [comment] 2022-07-02 01:54
This is the issue we were talking about @thebentern

**Comment by garthvh** [comment] 2022-09-11 14:16
Duplicate of #787

**Closed by garthvh** 2022-09-11 14:16 UTC
Labels: enhancement
